### ISSUE TITLE
Complete Software Requirements Specification Doc

### ISSUE THREAD

**Issue by vinnykuhnel** [Intro-to-SE-Lab-Fall-21-Section-2/Group_3#1]
https://docs.google.com/document/d/1Gv9cxPbyveTkTXbEhhSqcHAvmW7gksor/edit?usp=sharing&ouid=103128247114190854233&rtpof=true&sd=true

**Comment by R-Ledezma** [comment]
To solve this issue, we broke up the document into sections in order to distribute the work. Once we all filled in our sections, we all met up to review and edit the document as a whole. Now that we are content the issue has been resolved.
