### ISSUE TITLE
Interface with Mail Providers

### ISSUE THREAD

**Issue by vinnykuhnel** [Intro-to-SE-Lab-Fall-21-Section-2/Group_3#7]
Figure out how to interface and sync with a mail provider.

**Comment by vinnykuhnel** [comment]
Find out how to log into a mail service provider through python.
There is a good overview here:
https://linuxhint.com/send_email_python/

**Comment by davidpatel77** [comment]
We were able to pull our emails from a mail service provider and parse them.
